# Generated by Django 4.1 on 2022-08-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=220)),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='media/blog')),
                ('blog_content', models.TextField(max_length=2200)),
            ],
        ),
    ]
